[content_manipulation]
	wrapText = "REMAINING_WIDTH"
	overwriteVanillaWrapping = true

[positioning]
	preventVanillaClamping = false
	onlyRepositionHoverTooltips = false
	useYACLTooltipPositioner = true