configVersion = 2

[general]
	enableInThirdPerson = false
	turningRollAccumulation = 1.0
	turningRollIntensity = 2.0
	turningRollSmoothing = 1.0
	cameraSwayIntensity = 0.5
	cameraSwayFrequency = 0.2
	cameraSwayFadeInDelay = 3.0

[walking]
	strafingRollFactor = 10.0
	horizontalVelocitySmoothingFactor = 2.0

[swimming]
	horizontalVelocitySmoothingFactor = 2.0

[flying]
	horizontalVelocitySmoothingFactor = 2.0

[mounts]
	horizontalVelocitySmoothingFactor = 2.0

[vehicles]
	horizontalVelocitySmoothingFactor = 2.0