configVersion = 2

[general]
	enableInThirdPerson = false
	turningRollAccumulation = 1.0
	turningRollIntensity = 2.0
	turningRollSmoothing = 1.0
	cameraSwayIntensity = 0.0
	cameraSwayFrequency = 0.0
	cameraSwayFadeInDelay = 0.0
	cameraSwayFadeInLength = 0.0
	cameraSwayFadeOutLength = 0.0

[walking]
	strafingRollFactor = 10.0
	horizontalVelocitySmoothingFactor = 2.0

[swimming]
	horizontalVelocitySmoothingFactor = 2.0

[flying]
	horizontalVelocitySmoothingFactor = 2.0

[mounts]
	horizontalVelocitySmoothingFactor = 2.0

[vehicles]
	horizontalVelocitySmoothingFactor = 2.0