mod_badges = [
	"connector=!sinytra_neoforge, !library, core",
	"connectorextras=!sinytra_neoforge, !library, core",
	"fabric_api=!sinytra_neoforge, !library, core",
	"architectury=library",
	"balm=library",
	"cloth_config=library",
	"collective=library",
	"configurable=library",
	"cristellib=library",
	"fzzy_config=library",
	"gml=library",
	"konkrete=library",
	"kotlinforforge=library",
	"melody=library",
	"midnightlib=library",
	"mru=library",
	"octolib=library",
	"puzzleslib=library",
	"yet_another_config_lib_v3=library",
	"continuity=!sinytra_fabric, sinytra_neoforge",
	"badhorsefix=!sinytra_neoforge, patches",
	"citresewn_neopatcher=!sinytra_neoforge, patches",
	"sinytra1343=!sinytra_neoforge, patches",
	"irisblockcompat=!sinytra_neoforge, patches",
	"modelfix=!sinytra_neoforge, patches",
	"sspb=!sinytra_neoforge, patches",
	"mod_menu=!sinytra_neoforge, ports",
	"better_tooltips=!sinytra_neoforge, ports",
	"eatinganimation=!sinytra_neoforge, ports",
	"enhancedtooltips=!sinytra_neoforge, ports",
	"explosiveenhancement=!sinytra_neoforge, ports",
	"fallingleaves=!sinytra_neoforge, ports",
	"krypton=!sinytra_neoforge, ports",
	"mixintracereforged=!sinytra_neoforge, ports",
	"scalablelux=!sinytra_neoforge, ports",
	"smoothswapping=!sinytra_neoforge, ports",
	"emi=!sinytra_neoforge, qol",
	"extra_mod_integrations=!sinytra_neoforge, qol",
	"emiffect=!sinytra_neoforge, qol",
	"emi_enchanting=!sinytra_neoforge, qol",
	"emi_loot=!sinytra_neoforge, qol",
	"emi_ores=!sinytra_neoforge, qol",
	"jade=!sinytra_neoforge, qol",
	"jadeaddons=!sinytra_neoforge, qol",
	"toomanyrecipeviewers=!sinytra_neoforge, qol",
	"xaerominimap=!sinytra_neoforge, qol",
	"xaeroworldmap=!sinytra_neoforge, qol",
	"chunky=!sinytra_neoforge, technical",
	"chunkyborder=!sinytra_neoforge, technical",
	"configureddefaults=!sinytra_neoforge, technical",
	"defaultoptions=!sinytra_neoforge, technical",
	"hideexperimentalwarning=!sinytra_neoforge, technical",
	"resourcepackoverrides=!sinytra_neoforge, technical",
	"amplified_nether=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtaverns=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsancientcityoverhaul=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsnetherfortressoverhaul=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernspillageroutpostoverhaul=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsstrongholdoverhaul=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsswamphutoverhaul=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsdeserttemplereplacement=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsjungletemplereplacement=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsoceanmonumentreplacement=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernswoodlandmansionreplacement=!sinytra_neoforge, worldgen",
	"mr_dungeons_andtavernsendcastlestandalone=!sinytra_neoforge, worldgen",
	"mr_lukis_ancientcities=!sinytra_neoforge, worldgen",
	"mr_lukis_crazychambers=!sinytra_neoforge, worldgen",
	"mr_lukis_grandcapitals=!sinytra_neoforge, worldgen",
	"nullscape=!sinytra_neoforge, worldgen",
	"structory=!sinytra_neoforge, worldgen",
	"structory_towers=!sinytra_neoforge, worldgen",
	"terralith=!sinytra_neoforge, worldgen",
	"mr_remove_terralithintromessage=!sinytra_neoforge, worldgen",
	"t_and_t=!sinytra_neoforge, worldgen",
	"mr_trek=!sinytra_neoforge, worldgen"
]

mod_parents = [
	"connector=fabric_api",
	"sodium=sodium_extra, reeses_sodium_options",
	"sounds=more_sounds",
	"emi=extra_mod_integrations, emiffect, emi_enchanting, emi_loot, emi_ores",
	"jade=jadeaddons",
	"chunky=chunkyborder",
	"xaeroworldmap=xaerominimap",
	#"mr_dungeons_andtaverns=mr_dungeons_andtavernsancientcityoverhaul, mr_dungeons_andtavernsnetherfortressoverhaul, mr_dungeons_andtavernspillageroutpostoverhaul, mr_dungeons_andtavernsstrongholdoverhaul, mr_dungeons_andtavernsswamphutoverhaul, mr_dungeons_andtavernsdeserttemplereplacement, mr_dungeons_andtavernsjungletemplereplacement, mr_dungeons_andtavernsoceanmonumentreplacement, mr_dungeons_andtavernswoodlandmansionreplacement, mr_dungeons_andtavernsendcastlestandalone",
	"mr_lukis_grandcapitals=mr_lukis_ancientcities, mr_lukis_crazychambers",
	"structory=structory_towers",
	"terralith=mr_remove_terralithintromessage"
]

[main]
	compact_list = true
	mods_button_style = "REPLACE_REALMS"
	mod_count_location = "NONE"
	easter_eggs = false

[hide]
	show_libraries = true
	hide_badge = ["client"]
	hidden_mods = [
		"c2me_base",
		"c2me_client_uncapvd",
		"c2me_fixes_chunkio_threading_issues",
		"c2me_fixes_general_threading_issues",
		"c2me_fixes_worldgen_threading_issues",
		"c2me_fixes_worldgen_vanilla_bugs",
		"c2me_notickvd",
		"c2me_opts_allocs",
		"c2me_opts_chunkio",
		"c2me_opts_dfc",
		"c2me_opts_math",
		"c2me_opts_natives_math",
		"c2me_opts_scheduling",
		"c2me_opts_worldgen_general",
		"c2me_opts_worldgen_vanilla",
		"c2me_rewrites_chunk_serializer",
		"c2me_rewrites_chunk_system",
		"c2me_rewrites_chunkio",
		"c2me_server_utils",
		"c2me_threading_lighting",
		"citresewn_defaults",
		"commongroovylibrary",
		"conditional_mixin",
		"connectorextras_emi_bridge",
		"connectorextras_energy_bridge",
		"connectorextras_jei_bridge",
		"connectorextras_kubejs_bridge",
		"connectorextras_modmenu_bridge",
		"connectorextras_pehkui_bridge",
		"connectorextras_rei_bridge",
		"connectorextras_terrablender_bridge",
        "extra_mod_integrations_actually_additions",
        "extra_mod_integrations_chipped",
        "extra_mod_integrations_core",
        "extra_mod_integrations_farmers_delight",
        "extra_mod_integrations_irons_spellbooks",
        "extra_mod_integrations_pneumaticcraft",
        "extra_mod_integrations_rechiseled",
        "extra_mod_integrations_reliquary",
		"fabric-api",
		"java",
        "jei",
		"kirin",
		"kuma_api",
		"lambdynlights_api",
		"minecraft",
		"modmenu",
		"neoforge",
		"placeholder_api",
		"pride",
		"spruceui",
		"transition",
		"trender",
		"yumi_mc_libraries"
	]
	hide_mod_links = true
	hide_mod_license = true
	hide_mod_credits = true